name: Publish site
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.A6_BOT_PAT_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
